stages:
  - test
  - build-run

Test:
  stage: test
  script:
    - python -m unittest discover test
  image: python:slim
  tags:
    - gitlab-org-docker

Build-Run:
  stage: build-run
  script:
    - python -m src.calculadora.main
  image: python:slim
  tags:
    - gitlab-org-docker
    